#!/usr/bin/env node
import * as fs from "fs";
import { toString } from '@carbon/icon-helpers';
import path from "path";

const iconsRaw = fs.readFileSync('./node_modules/@carbon/icons/metadata.json');

const icons = JSON.parse(iconsRaw)

function ticked(str) {
    return "`" + str + "`"
}

function template(svg) {

return `
// Generated by carbon-icons-lit
import { svg } from "lit-html";

export default svg${ticked(svg)};
`
}


const indexJs = icons.icons.map(icon => {
    return icon.output.map(output => {
        const {moduleName, filepath, descriptor} = output

        const svg = toString(descriptor)
        console.log(svg)

        const folder = path.dirname(filepath)
        fs.mkdirSync(`./src/${folder}`, {recursive: true})
        
        fs.writeFileSync(`./src/${filepath.replace(".js", ".ts")}`, template(svg), {encoding: "utf8"});

        return `export { default as ${moduleName} } from './${filepath}'`
    }).join("\n")
}).join("\n\n");

fs.writeFileSync(`./src/index.ts`, indexJs, {encoding: "utf8"})

fs.copyFileSync("package.json", "dist/package.json")